import "server-only";
import { formatUnits, parseEventLogs, type Log, type PublicClient } from "viem";
import { fetchAllVaultCreations } from "../dashboard/vaultDirectory";
import { fetchNewLogs } from "../incrementalLogScan";
import type { ChainDef } from "../chains";

export interface ReferredVolume {
  chainId: number;
  chainName: string;
  tokenSymbol: string;
  totalDeposited: number;
  vaultCount: number;
  // Activation signal (criterio elegido: primer depósito real) — see
  // app/api/referral/stats/route.ts's lazy-activation call.
  hasDeposit: boolean;
}

interface DepositAccumulator {
  totalRaw: bigint;
  hasDeposit: boolean;
}

// fetchNewLogs (see incrementalLogScan.ts) only returns the DELTA since the
// last call for a given cache key — callers are expected to fold that delta
// into their own running total, same as vaultDirectory.ts's directoryCache.
// Without this, a second call here would silently report only whatever
// Deposited events landed since the first call, not the vault's real total.
const depositCache = new Map<string, DepositAccumulator>();

/**
 * Volume generated by a single referred wallet on one chain, read directly
 * on-chain (no indexer — same incremental-scan primitives the protocol
 * dashboard already uses). 1) find the referred wallet's own vault(s) via
 * the factory's VaultCreated directory (already cached), 2) sum every
 * Deposited event across just those vaults.
 */
export async function fetchReferredVolume(
  publicClient: PublicClient,
  chain: ChainDef,
  referred: `0x${string}`,
): Promise<ReferredVolume> {
  const directory = await fetchAllVaultCreations(publicClient, chain);
  const ownVaults = directory.filter((v) => v.owner.toLowerCase() === referred.toLowerCase());

  if (ownVaults.length === 0) {
    return { chainId: chain.id, chainName: chain.name, tokenSymbol: chain.stableSymbol, totalDeposited: 0, vaultCount: 0, hasDeposit: false };
  }

  await Promise.all(
    ownVaults.map(async (v) => {
      const cacheKey = `${chain.id}:${v.address.toLowerCase()}`;
      const acc = depositCache.get(cacheKey) ?? { totalRaw: 0n, hasDeposit: false };
      const freshLogs = await fetchNewLogs(`referral-deposits:${cacheKey}`, publicClient, {
        address: [v.address],
        fromBlock: chain.factoryDeployBlock,
      });
      const events = parseEventLogs({ abi: chain.vaultAbi, logs: freshLogs as Log[] }).filter(
        (l) => l.eventName === "Deposited",
      );
      for (const e of events) {
        const args = e.args as { investableAmount: bigint; reserveAmount: bigint };
        acc.totalRaw += args.investableAmount + args.reserveAmount;
        acc.hasDeposit = true;
      }
      depositCache.set(cacheKey, acc);
    }),
  );

  let totalRaw = 0n;
  let hasDeposit = false;
  for (const v of ownVaults) {
    const acc = depositCache.get(`${chain.id}:${v.address.toLowerCase()}`);
    if (!acc) continue;
    totalRaw += acc.totalRaw;
    hasDeposit = hasDeposit || acc.hasDeposit;
  }

  return {
    chainId: chain.id,
    chainName: chain.name,
    tokenSymbol: chain.stableSymbol,
    totalDeposited: Number(formatUnits(totalRaw, 6)),
    vaultCount: ownVaults.length,
    hasDeposit,
  };
}
